project:
  type: website
  output-dir: docs
  # render: 
  #   - "*.qmd"
  #   - "!*/slides.qmd"

website:
  title: "SISMID Module NUMBER Materials (2025)"
  # subtitle: "Introduction to R"
  # author:
  #   - name: "Zane Billings"
  #     url: https://wzbillings.com/
  #     affiliation: University of Georgia
  #     orcid: 0000-0002-0184-6134
  #   - name: "Amy Winter"
  #     url: https://publichealth.uga.edu/faculty-member/amy-k-winter/
  #     affiliation: University of Georgia
  #     orcid: 0000-0003-2737-7003
  # date: "2024-07-15"
  sidebar:
    style: docked
    search: true
    pinned: true
    tools: 
      - icon: github
        href: https://github.com/UGA-IDD/SISMID-2024
    contents: 
      - text: "Welcome!"
        href: index.qmd
      - text: "Course Schedule"
        href: schedule.qmd
      - text: "Course Resources"
        href: references.qmd
      - section: "Day 1"
        contents:
          - href: modules/Module01-Intro.qmd
            target: _blank
          - href: modules/CaseStudy01.qmd
            target: _blank
      - section: "Day 2"
        contents:
          - href: modules/ModuleXX-Iteration.qmd
            target: _blank
      - section: "Day 3"
  repo-url: https://github.com/UGA-IDD/SISMID-2024
  reader-mode: true
  # favicon: ./images/sismid2023-logo-green.png

# Default for table of contents
toc: true
toc-title: Page Items
toc-location: right

# Default knitr options
execute:
  echo: true
  message: true
  warning: true
  freeze: auto

engine: knitr

# Default author
author:
  - name: "Amy Winter"
    url: https://publichealth.uga.edu/faculty-member/amy-k-winter/
    orcid: 0000-0003-2737-7003
  - name: "Zane Billings"
    url: https://wzbillings.com/
    orcid: 0000-0002-0184-6134

# Default fields for citation
license: "CC BY-NC"

# bibliography: SISMID-Module.bib
# nocite: |
#   @*

format:
  html:
    theme:
      light: [cosmo, format/_fonts.scss, format/_light.scss, format/_callouts.scss]
      dark: [cosmo, format/_fonts.scss, format/_dark.scss, format/_callouts.scss]
    grid:
      sidebar-width: 270px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1rem
    code-copy: true
    code-fold: show
    code-overflow: wrap
    code-link: true
    code-tools: true
    code-line-numbers: true

# Extension Lua filters
filters:
  - line-highlight
